### ISSUE TITLE
Do we have to use powersync ?

### ISSUE THREAD

**Issue by volkankoc** [Gambley1/flutter-instagram-offline-first-clone#138]
Do we have to use powersync

I want to make this application. But I don't quite understand why powersync is used.
How to do without powersync

**Comment by Gambley1** [comment]
Please, refer to a discussion section in this github repository with such non-techical questions. Thanks.

**Comment by Gambley1** [comment]
Please, refer to a discussion section in this github repository with such non-techical questions. Thanks.
